### PR TITLE
Updating node

### PR DESCRIPTION
**Pull request by jpuri**
Updating node

### CODE REVIEW

**Review by Mrtenz — DISMISSED** [review]
Make sure to update `.nvmrc`, `README.md` and any workflows using Node 12 as well.

**Comment by jpuri** [comment]
This check should probably be removed now `Build, Lint, and Test / Build, Lint, and Test (12.x) (pull_request)`

**Comment by Gudahtt** [comment]
@jpuri you can adjust that here: https://github.com/MetaMask/providers/blob/main/.github/workflows/build-test-lint.yml#L14

**Comment by jpuri** [comment]
@Gudahtt , @Mrtenz : PR is updated.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Review by mcmire — APPROVED** [review]
Yup, LGTM too.

**Pull request merged**
