### PR TITLE
refactor: Use named `extension-port-stream` import for Vite compatibility

### PR DESCRIPTION
**Pull request by zouhangwithsweet**
- fix vite import error in development
- https://github.com/vitejs/vite/issues/9703

### CODE REVIEW

**Comment by zouhangwithsweet** [comment]
- [Reproduction](https://github.com/fisand/wagmi-wxt-starter/blob/main/entrypoints/sidepanel/wagmi.config.ts#L19)

**Comment by zouhangwithsweet** [comment]
Can you help me with a code review? @legobeat

**Comment by Mrtenz** [comment]
Rather than handling it here, what do you think about fixing this upstream, i.e., removing the default export from `extension-port-stream`?

cc @legobeat

**Comment by zouhangwithsweet** [comment]
> `extension-port-stream`?

Souds great. I just add the pr: https://github.com/MetaMask/extension-port-stream/pull/57

**Comment by rekmarks** [comment]
Once [this version](https://github.com/MetaMask/extension-port-stream/pull/58) of `extension-port-stream` is released, it should be added here and the default export of `PortDuplexStream` should be replaced with the named export.

**Review by rekmarks — APPROVED** [review]
LGTM!

**Pull request merged**
