### PR TITLE
5.2.0

### PR DESCRIPTION
**Pull request by rekmarks**
Pending: #55

### CODE REVIEW

**Comment by rekmarks** [comment]
@MetaMask/devs 👀for a version bump please!

**Review by Gudahtt — CHANGES_REQUESTED** [review]
The changelog should be updated as well

**Comment by rekmarks** [comment]
Updated changelog. ~but please approve #58 also.~

#58 was merged.

**Review by Gudahtt — APPROVED** [review]
LGTM!

**Pull request merged**
